$(document).ready(function(){
    $(".c-red").click(function(){
        $(".b-red").toggle();
    });
    $(".c-blue").click(function(){
        $(".b-blue").toggle();
    });
    $(".c-yellow").click(function(){
        $(".b-yellow").toggle();
    });
});